import { createFileRoute } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { metricsOptions } from '@/lib/factlens-api';
import { pageMeta } from '@/lib/page-meta';

export const Route = createFileRoute('/methodology')({ head: () => pageMeta('Methodology & Model Metrics — FactLens', 'Understand FactLens text preprocessing, TF-IDF features, classifier selection and evaluation limitations.'), loader: async ({ context }) => { await context.queryClient.ensureQueryData(metricsOptions); }, errorComponent: () => <main className="tool-page"><h1 className="page-heading">Methodology unavailable</h1><p role="alert">Please refresh to try again.</p></main>, notFoundComponent: () => <main className="tool-page"><h1 className="page-heading">Methodology not found</h1></main>, component: Methodology });
function Methodology() {
  const { data } = useSuspenseQuery(metricsOptions);
  return <main className="tool-page"><div className="eyebrow">FactLens / Behind the lens</div><h1 className="page-heading">How we read the signals.</h1><p className="max-w-2xl text-muted-foreground leading-relaxed mb-12">Transparent methods matter. FactLens learns linguistic patterns from labeled news text, rather than verifying individual facts against current sources.</p>{[['01', 'Prepare the text', 'Text is normalized, HTML and punctuation are removed, and stopwords are filtered. Stemming reduces related words to a common form.'], ['02', 'Identify patterns', 'TF-IDF represents individual words and word pairs as weighted features. The classifier learns how these features relate to the training labels.'], ['03', 'Compare the models', 'Logistic Regression, Naive Bayes, SVM and Random Forest are evaluated. The best model is selected by its test-set F1 score.']].map(([number, title, copy]) => <section className="method-row" key={number}><span className="text-muted-foreground text-sm">{number}</span><h2>{title}</h2><p>{copy}</p></section>)}<section className="mt-12"><h2 className="font-display text-3xl">Model evaluation</h2>{data ? <><p className="text-sm text-muted-foreground mt-3">Reported by the original FactLens service · {data.dataset_size.toLocaleString()} dataset examples · {data.test_size.toLocaleString()} test examples · Selected: {data.best_model}</p><div className="overflow-x-auto"><table className="model-table"><thead><tr><th>Model</th><th>Accuracy</th><th>Precision</th><th>Recall</th><th>F1</th></tr></thead><tbody>{Object.entries(data.models).map(([name, model]) => <tr key={name}><td className="font-medium">{name}{name === data.best_model ? ' *' : ''}</td>{[model.accuracy, model.precision, model.recall, model.f1_score].map((value, i) => <td key={i}>{(value * 100).toFixed(1)}%</td>)}</tr>)}</tbody></table></div><p className="status-message">These scores describe the service’s test dataset, not real-world factual accuracy. Dataset composition, synthetic examples, overlap and topic changes can substantially affect generalization.</p></> : <p className="status-message">Model metrics are temporarily unavailable. No scores are shown until the original analysis service responds.</p>}</section><section className="method-row"><span className="text-muted-foreground text-sm">04</span><h2>Know the limits</h2><p>Confidence measures the model’s certainty about its label, not the probability that a claim is true. Predictions can be wrong, particularly for unfamiliar topics, satire or short text. Always verify with primary sources.</p></section></main>;
}